{
 "title": "DietWater App",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Real Time Data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(php_app_http_requests_total[30s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Code 2xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(php_app_http_requests_total{status=\"200\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Code 4xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(php_app_http_requests_total{status=\"404\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status Code 5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(php_app_http_requests_total{status=\"500\"}[30s])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Response Time / Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(php_app_response_time_seconds_bucket[5m])))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(php_app_response_time_seconds_bucket[5m])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(php_app_response_time_seconds_bucket[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(php_app_response_time_seconds_bucket[5m])))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Requests %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "100 * rate(php_app_http_requests_total{status=\"500\"}[5m])\n  /\non(instance, job)\nsum by(instance, job)(rate(php_app_http_requests_total[5m]))",
     "legendFormat": "5xx"
    },
    {
     "expr": "100 * rate(php_app_http_requests_total{status=\"404\"}[5m])\n  /\non(instance, job)\nsum by(instance, job)(rate(php_app_http_requests_total[5m]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "100 * rate(php_app_http_requests_total{status=\"200\"}[5m])\n  /\non(instance, job)\nsum by(instance, job)(rate(php_app_http_requests_total[5m]))",
     "legendFormat": "2xx"
    }
   ]
  }
 ]
}